namespace ShooterLoop;

// Every sound effect in the game goes through here. Autoload, declared after GameManager in
// project.godot so GameManager.Instance already exists by the time _Ready runs and the saved volume
// can be read straight off it.
//
// The .wav files are generated by tools/gen_sfx.py -- see that script for the sound design itself.
// This class only decides *when* a sound is allowed to play, which in a game that fires five bullets
// a volley at fifty enemies turns out to be the harder half of the problem.
public partial class AudioManager : Node
{
    public static AudioManager Instance { get; private set; }

    public enum Sfx
    {
        Shoot, EnemyShoot, Hit, EnemyDie, Explosion, BossDie,
        PlayerHurt, Shield, Dodge, PlayerDie,
        Pickup, LevelUp, Countdown, RoundStart, RoundComplete, BossAlarm,
        UiClick, UiBuy, UiDenied, Modal,
    }

    public enum MusicTrack { None, Menu, Arena }

    // Bus names must match default_bus_layout.tres. SFX and Music both send to Master, which is what
    // makes the "General" slider work without multiplying anything in code.
    public const string SfxBus = "SFX";
    public const string MusicBus = "Music";
    public const string MasterBus = "Master";

    // File name, minimum seconds between two plays of this sound, and how far the pitch is allowed
    // to wander (as a fraction, so 0.08 = +/-8%).
    //
    // The interval is the anti-cacophony valve: Hit can be triggered a dozen times in one frame by a
    // piercing, ricocheting shot crossing a crowd, and every trigger past the first few is inaudible
    // anyway -- dropping them costs nothing and is what keeps a busy round legible. Sounds that fire
    // at most once per event (level up, round start, a death) get 0 and are never dropped.
    //
    // The jitter is what stops repetition fatigue. The same 85ms blip 300 times a run reads as a
    // stuck machine; the same blip detuned a few percent each time reads as a gun.
    private static readonly (Sfx Kind, string File, float MinInterval, float Jitter)[] Defs =
    {
        (Sfx.Shoot,         "shoot",          0.050f, 0.08f),
        (Sfx.EnemyShoot,    "enemy_shoot",    0.060f, 0.10f),
        (Sfx.Hit,           "hit",            0.045f, 0.12f),
        (Sfx.EnemyDie,      "enemy_die",      0.050f, 0.10f),
        (Sfx.Explosion,     "explosion",      0.080f, 0.08f),
        (Sfx.BossDie,       "boss_die",       0f,     0f),
        (Sfx.PlayerHurt,    "player_hurt",    0.150f, 0.04f),
        (Sfx.Shield,        "shield",         0.100f, 0.05f),
        (Sfx.Dodge,         "dodge",          0.100f, 0.08f),
        (Sfx.PlayerDie,     "player_die",     0f,     0f),
        (Sfx.Pickup,        "pickup",         0.040f, 0.10f),
        (Sfx.LevelUp,       "level_up",       0f,     0f),
        (Sfx.Countdown,     "countdown",      0f,     0f),
        (Sfx.RoundStart,    "round_start",    0f,     0f),
        (Sfx.BossAlarm,     "boss_alarm",     0f,     0f),
        (Sfx.RoundComplete, "round_complete", 0f,     0f),
        (Sfx.UiClick,       "ui_click",       0.030f, 0.05f),
        (Sfx.UiBuy,         "ui_buy",         0f,     0f),
        (Sfx.UiDenied,      "ui_denied",      0.100f, 0f),
        (Sfx.Modal,         "modal",          0.050f, 0.06f),
    };

    private const string AudioDir = "res://Assets/Audio/";

    // Comfortably more than the cooldowns above can let through at once. When it is exceeded
    // PlayStream just returns an invalid id and the sound is dropped, which is the correct failure
    // for a sound nobody would have picked out of the mix anyway.
    private const int Polyphony = 24;

    private readonly Dictionary<Sfx, AudioStream> _streams = new();
    private readonly Dictionary<Sfx, (float MinInterval, float Jitter)> _rules = new();
    private readonly Dictionary<Sfx, ulong> _lastPlayedMsec = new();
    private readonly Random _rng = new();

    private AudioStreamPlaybackPolyphonic _playback;

    private readonly Dictionary<MusicTrack, AudioStream> _music = new();
    private AudioStreamPlayer _musicPlayer;
    private MusicTrack _currentTrack = MusicTrack.None;
    private Tween _musicFade;

    private const float MusicFadeSeconds = 0.6f;

    public override void _Ready()
    {
        Instance = this;

        // Not optional. The five modals (PauseMenu, Shop, UpgradePicker, GameOverScreen,
        // ConfirmDialog) run with ProcessMode.Always because the tree is paused the whole time
        // they're up, and an autoload defaults to Pausable. Without this the shop and pause-menu
        // buttons would be silent exactly when they're being used, and the death sting would never
        // play at all -- NotifyPlayerDied calls Pause() on the very next line.
        ProcessMode = ProcessModeEnum.Always;

        var player = new AudioStreamPlayer
        {
            // One player with a polyphonic stream, rather than a hand-rolled pool of N
            // AudioStreamPlayers to round-robin through. Same result, none of the bookkeeping.
            Stream = new AudioStreamPolyphonic { Polyphony = Polyphony },
            Bus = SfxBus,
            ProcessMode = ProcessModeEnum.Always,
        };
        AddChild(player);
        player.Play();
        _playback = player.GetStreamPlayback() as AudioStreamPlaybackPolyphonic;

        // Child of this node, so it inherits ProcessMode.Always and keeps playing while the tree is
        // paused. That's deliberate: the shop and the pause menu shouldn't drop into silence.
        _musicPlayer = new AudioStreamPlayer
        {
            Bus = MusicBus,
            ProcessMode = ProcessModeEnum.Always,
        };
        AddChild(_musicPlayer);

        LoadStreams();
        LoadMusic();

        // Pulled from GameManager rather than pushed by it: autoloads initialise in declaration
        // order and this one is listed second, so the saved values are already loaded by now.
        var gm = GameManager.Instance;
        ApplyBusVolume(MasterBus, gm?.MasterVolume ?? 1f);
        ApplyBusVolume(SfxBus, gm?.SfxVolume ?? 1f);
        ApplyBusVolume(MusicBus, gm?.MusicVolume ?? 1f);
    }

    // A missing file has to mean silence, never a crash. The .wav.import sidecars are written by the
    // Godot editor, not by the generator script, so there is a real window -- right after running
    // tools/gen_sfx.py and before opening the editor -- where these paths don't resolve yet.
    private void LoadStreams()
    {
        foreach (var (kind, file, minInterval, jitter) in Defs)
        {
            _rules[kind] = (minInterval, jitter);
            _lastPlayedMsec[kind] = 0;

            string path = $"{AudioDir}{file}.wav";
            if (ResourceLoader.Exists(path))
                _streams[kind] = GD.Load<AudioStream>(path);
        }
    }

    // Looping is set here in code rather than in each .wav.import's edit/loop_mode. The sidecars are
    // generated by the Godot editor and are easy to lose or regenerate, and a track that silently
    // stops looping because a file nobody reads got rewritten is a miserable bug to chase. Setting it
    // on the loaded resource makes the behaviour visible in the code that depends on it.
    private void LoadMusic()
    {
        foreach (var (track, file) in new[] { (MusicTrack.Menu, "music_menu"), (MusicTrack.Arena, "music_arena") })
        {
            string path = $"{AudioDir}{file}.wav";
            if (!ResourceLoader.Exists(path)) continue;

            var stream = GD.Load<AudioStream>(path);
            if (stream is AudioStreamWav wav)
            {
                wav.LoopMode = AudioStreamWav.LoopModeEnum.Forward;
                wav.LoopBegin = 0;
                wav.LoopEnd = wav.Data.Length / 2;   // 16-bit mono: two bytes per frame
            }
            _music[track] = stream;
        }
    }

    // False when no music track is present, which is the current state: the generated chiptune loops
    // were cut for being unpleasant, and nothing replaced them yet. The playback plumbing below is
    // kept because it costs little and a real track only has to be dropped into Assets/Audio to work
    // — but the options screen reads this so it doesn't show a slider that controls nothing.
    public bool HasMusic => _music.Count > 0;

    // Crossfades to `track`. Calling it with the track that's already playing does nothing, which is
    // what stops the menu theme restarting from the top every time the player backs out of a submenu.
    public void PlayMusic(MusicTrack track)
    {
        if (_musicPlayer == null || track == _currentTrack) return;
        if (!_music.TryGetValue(track, out var stream) || stream == null) return;

        _currentTrack = track;
        _musicFade?.Kill();

        // Created on this node, which is ProcessMode.Always — a tween owned by a pausable node would
        // freeze mid-fade the moment the shop opened and leave the music stuck at half volume.
        _musicFade = CreateTween();

        if (_musicPlayer.Playing)
            _musicFade.TweenProperty(_musicPlayer, "volume_db", -40f, MusicFadeSeconds * 0.5f);

        _musicFade.TweenCallback(Callable.From(() =>
        {
            _musicPlayer.Stream = stream;
            _musicPlayer.VolumeDb = -40f;
            _musicPlayer.Play();
        }));
        _musicFade.TweenProperty(_musicPlayer, "volume_db", 0f, MusicFadeSeconds);
    }

    // volumeDb shifts one call relative to the sound's baked-in level, for the rare case where the
    // same effect wants to be quieter in one context than another.
    public void Play(Sfx sound, float volumeDb = 0f)
    {
        if (_playback == null) return;
        if (!_streams.TryGetValue(sound, out var stream) || stream == null) return;

        var (minInterval, jitter) = _rules[sound];

        // Time.GetTicksMsec rather than a delta accumulated in _Process: it keeps counting while the
        // tree is paused, which is when the UI sounds happen.
        ulong now = Time.GetTicksMsec();
        if (minInterval > 0f)
        {
            if (now - _lastPlayedMsec[sound] < (ulong)(minInterval * 1000f)) return;
            _lastPlayedMsec[sound] = now;
        }

        float pitch = jitter > 0f
            ? 1f + (float)(_rng.NextDouble() * 2.0 - 1.0) * jitter
            : 1f;

        _playback.PlayStream(stream, 0f, volumeDb, pitch);
    }

    // One method for all three sliders. Master needs no special handling: SFX and Music send to it,
    // so attenuating Master attenuates both by definition of a send, rather than by any arithmetic
    // here that every future sound source would have to remember to apply.
    public void ApplyBusVolume(string busName, float linear)
    {
        int bus = AudioServer.GetBusIndex(busName);
        if (bus < 0) return;

        // Muting rather than trusting LinearToDb at the bottom of the range: 0 linear is -inf dB,
        // and a slider sitting at 0 should be provably silent rather than very quiet.
        AudioServer.SetBusMute(bus, linear <= 0.001f);
        AudioServer.SetBusVolumeDb(bus, Mathf.LinearToDb(Mathf.Max(linear, 0.001f)));
    }
}
